Azure pipelines (#1)

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,70 +1,89 @@
 trigger:
-    - master
+  batch: true
+  branches:
+    include:
+      - master
 
 pool:
-    name: Hosted Ubuntu 1604
+  name: Hosted Ubuntu 1604
 
 variables:
-    bot.image: 'carlhugo/ogechobot'
-    bot.imageName: 'ogechobot'
-    bot.sshEndpoint: 'Google Cloud Bots'
-    bot.dockerRegistryEndpoint: 'Docker Hub'
-    bot.envFile: 'ogechobot.env'
+  bot.image: 'carlhugo/ogechobot'
+  bot.imageName: 'ogechobot'
+  bot.sshEndpoint: 'Google Cloud Bots'
+  bot.dockerRegistryEndpoint: 'Docker Hub'
+  bot.envFile: 'ogechobot.env'
 
-steps:
-    - bash: |
-          PACKAGE_VERSION=$(grep '"version":' package.json | cut -d\" -f4)
-          echo "##vso[build.updatebuildnumber]$PACKAGE_VERSION"
-      displayName: 'Update Build Number'
+jobs:
+- job: Build
+  displayName: Build Image
+  steps:
+  - bash: |
+        PACKAGE_VERSION=$(grep '"version":' package.json | cut -d\" -f4)
+        echo "##vso[build.updatebuildnumber]$PACKAGE_VERSION"
+    displayName: 'Update Build Number'
 
-    - task: Docker@1
-      displayName: 'Build an image'
-      inputs:
-          containerregistrytype: 'Container Registry'
-          dockerRegistryEndpoint: $(bot.dockerRegistryEndpoint)
-          imageName: '$(bot.image):$(Build.BuildNumber)'
+  - task: Docker@1
+    displayName: 'Build an image'
+    inputs:
+        containerregistrytype: 'Container Registry'
+        dockerRegistryEndpoint: $(bot.dockerRegistryEndpoint)
+        imageName: '$(bot.image):$(Build.BuildNumber)'
+    enabled: true
 
-    - task: Docker@1
-      displayName: 'Push an image'
-      inputs:
-          containerregistrytype: 'Container Registry'
-          dockerRegistryEndpoint: $(bot.dockerRegistryEndpoint)
-          command: 'Push an image'
-          imageName: '$(bot.image):$(Build.BuildNumber)'
+  - task: Docker@1
+    displayName: 'Push an image'
+    inputs:
+        containerregistrytype: 'Container Registry'
+        dockerRegistryEndpoint: $(bot.dockerRegistryEndpoint)
+        command: 'Push an image'
+        imageName: '$(bot.image):$(Build.BuildNumber)'
+    enabled: true
+    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
 
-    - task: DownloadSecureFile@1
-      displayName: 'Download secure file'
-      inputs:
-          secureFile: $(bot.envFile)
+- job: Deploy
+  displayName: Deploy Container
+  dependsOn: Build
+  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
+  steps:
+  - bash: |
+      PACKAGE_VERSION=$(grep '"version":' package.json | cut -d\" -f4)
+      echo "##vso[build.updatebuildnumber]$PACKAGE_VERSION"
+    displayName: 'Update Build Number'
 
-    - bash: 'cp $(configs.secureFilePath) $(Build.SourcesDirectory)/$(bot.envFile)'
-      displayName: 'Bash Script'
+  - task: DownloadSecureFile@1
+    name: environment
+    displayName: 'Download secure file'
+    inputs:
+        secureFile: $(bot.envFile)
 
-    - task: CopyFilesOverSSH@0
-      displayName: 'Securely copy files to the remote machine'
-      inputs:
-          sshEndpoint: $(bot.sshEndpoint)
-          sourceFolder: '$(Build.SourcesDirectory)'
-          contents: $(bot.envFile)
-          failOnEmptySource: true
+  - bash: 'cp $(environment.secureFilePath) $(Build.SourcesDirectory)/$(bot.envFile)'
+    displayName: 'Bash Script'
+    enabled: true
 
-    - task: SSH@0
-      displayName: 'Run shell inline on remote machine'
-      inputs:
-          sshEndpoint: $(bot.sshEndpoint)
-          runOptions: inline
-          inline: |
-              # Pull the new image
-              docker pull "$(bot.image):$(Build.BuildNumber)"
+  - task: CopyFilesOverSSH@0
+    displayName: 'Securely copy files to the remote machine'
+    inputs:
+        sshEndpoint: $(bot.sshEndpoint)
+        sourceFolder: '$(Build.SourcesDirectory)'
+        contents: $(bot.envFile)
+        failOnEmptySource: true
+    enabled: true
 
-              # Stop the running container
-              if (docker ps | grep $(bot.imageName))
-              then
-                  docker kill $(docker ps | grep $(bot.imageName) | cut -c 1-12)
-              fi
-
-              # Run the new image
-              docker run --restart=always -d "$(bot.image):$(Build.BuildNumber)"
-
-              # Cleanup
-              docker system prune -f -a
+  - task: SSH@0
+    displayName: 'Run shell inline on remote machine'
+    inputs:
+        sshEndpoint: $(bot.sshEndpoint)
+        commands: |
+            # Pull the new image
+            docker pull $(bot.image):$(Build.BuildNumber)
+            
+            # Kill/Remove the running container
+            docker ps | grep $(bot.imageName) && docker kill $(bot.imageName) && docker rm $(bot.imageName) || echo "No container named $(bot.imageName) is running."
+            
+            # Run the new image
+            docker run --env-file ./$(bot.envFile) --restart=always --name $(bot.imageName) -d $(bot.image):$(Build.BuildNumber)
+            
+            # Cleanup
+            docker system prune -f -a
+    enabled: true
